
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="lanternmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Realistic Lanterns" #mandatory
logoFile="examplemod.png" #optional
authors="Jk" #optional
description='''

Replaces vanilla lanterns with lanterns that have limited lifetime.

'''
[[dependencies.lanternmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
